import {FIRST_ROUTE,ITEMS} from './route.js';
import {createPalaceScene} from './scene.js';
import {STORAGE_KEY,loadFrom,saveTo,makeReview,upsertReview,rescheduleReview,localDate} from './storage.js';
import {ASSOCIATIONS,freshSession,stableSession,currentPair,outcomeCounts,recordOutcome,validateHomeNames,checkRoutePick} from './learning.js';

const $=selector=>document.querySelector(selector);
const el={app:$('#app'),world:$('#world'),card:$('#actionCard'),title:$('#cardTitle'),text:$('#cardText'),eye:$('#eyebrow'),art:$('#itemArt'),form:$('#formArea'),choices:$('#choices'),feedback:$('#feedback'),primary:$('#primary'),secondary:$('#secondary'),travel:$('#travel'),loading:$('#loading'),progress:$('#progress'),progressLabel:$('#progressLabel'),saveWarning:$('#saveWarning'),settings:$('#settings')};
const loaded=loadFrom(localStorage);let data=loaded.data,sceneAPI,renderToken=0,audio,lastSaveOK=loaded.ok;
const osReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const prefs={sound:data.prefs.sound===true,reduced:typeof data.prefs.reduced==='boolean'?data.prefs.reduced:osReduced};
if(!loaded.ok)showSaveWarning(loaded.warning);
const inspect=new URLSearchParams(location.search).has('inspect');$('#inspect').hidden=!inspect;

function showSaveWarning(message){el.saveWarning.hidden=!message;el.saveWarning.textContent=message||'';}
function save(){data.prefs={...prefs};const result=saveTo(localStorage,data);lastSaveOK=result.ok;if(!result.ok)showSaveWarning(result.warning);return result.ok;}
function saveSession(){if(data.session)data.session.updatedAt=new Date().toISOString();save();}
function setSession(patch){data.session={...data.session,...patch,updatedAt:new Date().toISOString()};saveSession();}
function blank(){el.form.replaceChildren();el.choices.replaceChildren();el.feedback.textContent='';el.art.replaceChildren();el.card.classList.remove('landing');el.primary.hidden=false;el.secondary.hidden=true;}
function card(eye,title,text,art=-1,{landing=false}={}){blank();el.card.hidden=false;el.card.classList.toggle('landing',landing);el.eye.textContent=eye;el.title.textContent=title;el.text.textContent=text;if(art>=0&&sceneAPI?.thumbnails[art]){const image=new Image();image.src=sceneAPI.thumbnails[art];image.alt='';el.art.append(image);}}
function primary(label,handler){el.primary.textContent=label;el.primary.disabled=false;el.primary.onclick=()=>handler?.();}
function secondary(label,handler,css=''){el.secondary.hidden=!label;el.secondary.textContent=label;el.secondary.className=`textButton ${css}`.trim();el.secondary.onclick=()=>handler?.();}
function button(label,handler,{wide=false,art=-1}={}){const value=document.createElement('button');value.type='button';value.className=`choice${wide?' wide':''}`;if(art>=0&&sceneAPI.thumbnails[art]){const image=new Image();image.src=sceneAPI.thumbnails[art];image.alt='';value.append(image);}const span=document.createElement('span');span.textContent=label;value.append(span);value.onclick=handler;el.choices.append(value);return value;}
function field(label,value='',type='textarea'){const wrap=document.createElement('label');wrap.className='field';const caption=document.createElement('span');caption.textContent=label;const input=document.createElement(type);input.value=value;input.maxLength=type==='input'?24:120;wrap.append(caption,input);el.form.append(wrap);return input;}
function playSound(kind='step'){if(!prefs.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='success'?[523,659,784]:[440,554];notes.forEach((frequency,index)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),time=audio.currentTime+index*.1;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.001,time);gain.gain.linearRampToValueAtTime(.05,time+.02);gain.gain.exponentialRampToValueAtTime(.001,time+.48);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(time);oscillator.stop(time+.5);});}catch{/* optional */}}
function progress(stage){const step=stage==='preview'||stage==='routeCheck'?0:stage==='associate'?1:stage==='recall'||stage==='result'?2:-1;const labels=stage.startsWith('home')?'自宅の3地点で応用':step===0?'場所を知る':step===1?'自分で結ぶ':step===2?'思い出す':'まず3つの場所へ';el.progressLabel.textContent=labels;[...el.progress.querySelectorAll('li')].forEach((li,index)=>{li.classList.toggle('done',step>=0&&index<step);li.classList.toggle('current',index===step);});}
async function travel(point,label,token){el.card.hidden=true;el.travel.hidden=false;el.travel.textContent=label;sceneAPI.hideItems();sceneAPI.mark(point.order-1,true);await sceneAPI.moveTo(point);if(token!==renderToken)return false;el.travel.hidden=true;return true;}
function nextStage(stage,index=0,extra={}){data.session=stableSession({...data.session,stage,index,assistedUsed:false,...extra});saveSession();render();}

async function render(){const token=++renderToken,session=data.session;el.app.dataset.phase=session?.stage||'landing';progress(session?.stage||'landing');if(!session){renderLanding();return;}switch(session.stage){case'preview':await renderPreview(token);break;case'routeCheck':renderRouteCheck();break;case'associate':await renderAssociate(token);break;case'recall':await renderRecall(token);break;case'result':renderResult();break;case'homeSetup':renderHomeSetup();break;case'homeAssociate':renderHomeAssociate();break;case'homeRecall':renderHomeRecall();break;case'homeResult':renderHomeResult();break;default:data.session=null;save();renderLanding();}}
function renderLanding(){sceneAPI.showOverview();progress('landing');const due=data.reviews.find(review=>review.dueDate<=localDate());if(data.session){return;}card('体験版 · 神社の入口3地点','景色を歩き、自分で結び、思い出す。',due?'今日は短い復習の日です。答えを隠して3地点を思い出します。':'駐車場から鳥居まで。まずは品物なしで景色を見ます。',-1,{landing:true});if(due){primary('今日の復習を始める →',()=>{data.session={...freshSession(),stage:'recall',associations:{...data.associations},reviewId:due.id,reviewStep:due.step};saveSession();render();});secondary('最初から練習する',()=>{data.session=freshSession();saveSession();render();});}else{primary('3つの場所へ →',()=>{data.session=freshSession();saveSession();render();});if(data.lastResult)secondary('前回の結果を見る',()=>{data.session={...freshSession(),stage:'result',outcomes:data.lastResult.outcomes};saveSession();render();});}}
function showContinueLanding(){renderToken++;sceneAPI.showOverview();card('続きが保存されています','途中から、同じ画面へ戻れます。','移動や演出の途中ではなく、直前の安定した場面から再開します。',-1,{landing:true});primary('続きから →',render);secondary('新しく始める',()=>{card('途中の記録を置き換えますか？','新しく3地点を歩きます。','前回の結果と明日の復習予定は残ります。途中の進みだけを最初に戻します。');primary('新しく始める',()=>{data.session=freshSession();saveSession();render();});secondary('続きへ戻る',render);},'danger');}

async function renderPreview(token){const s=data.session,{point}=currentPair(s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.hideItems();card(`下見 ${s.index+1} / 3`,point.label,s.index===0?'広い足元と、低い車止め。':s.index===1?'木の枠と、山へ続く道。':'赤い柱。ここから森の参道へ。');primary(s.index<2?'次の場所へ →':'順路を確かめる →',()=>s.index<2?nextStage('preview',s.index+1):nextStage('routeCheck',0,{routeOrder:[]}));if(s.index>0)secondary('ひとつ前へ',()=>nextStage('preview',s.index-1));}
function renderRouteCheck(){sceneAPI.showOverview();const s=data.session,done=s.routeOrder.length;card('下見のあと',done===3?'順路がつながりました。':`${done+1}番目は、どこ？`,done===3?'駐車場から少しずつ山を登ります。':'見た順に選んでください。これは能力の評価ではありません。');if(done<3){['torii','parking','guide'].forEach(id=>{const point=FIRST_ROUTE.find(row=>row.id===id),choice=button(point.label,()=>{const result=checkRoutePick(s.routeOrder,id);if(!result.ok){choice.classList.add('wrong');el.feedback.textContent=`もう一度。${done===0?'最初に見た場所':'次に見た場所'}を選びます。`;return;}setSession({routeOrder:result.order});playSound();renderRouteCheck();},{wide:false});if(s.routeOrder.includes(id))choice.disabled=true;});el.primary.hidden=true;secondary('下見に戻る',()=>nextStage('preview',0));}else{primary('品物と結ぶ →',()=>nextStage('associate',0));secondary('もう一度、下見する',()=>nextStage('preview',0));}}

async function renderAssociate(token){const s=data.session,{point,item}=currentPair(s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.mark(s.index,false);if(s.index===0){const watched=Boolean(s.associations.parking);if(watched)sceneAPI.playAssociation(0,'swell',false);else sceneAPI.setItem(0,false);card('見本 · 1 / 3','車止めと、ぎゅうにゅう。',watched?ASSOCIATIONS.parking:'まず、場所と品物が作用する見本を見ます。',watched?0:-1);if(!watched){primary('見本を見る',()=>{sceneAPI.playAssociation(0,'swell',true);playSound();setSession({associations:{...s.associations,parking:ASSOCIATIONS.parking}});card('頭の中なら、こんなことも。','牛乳が大きくなって車止めへ。',ASSOCIATIONS.parking,0);primary('景色を覚えた →',()=>nextStage('associate',1));});}else primary('景色を覚えた →',()=>nextStage('associate',1));return;}
  sceneAPI.setItem(s.index,true,false);
  if(s.index===1){const picked=s.associations.guide;if(picked)sceneAPI.playAssociation(1,picked===ASSOCIATIONS.guideChoices[0]?'roll':'fit',false);else sceneAPI.setItem(1,true,false);card('選ぶ · 2 / 3','案内板と、りんご。',picked||'場所と品物が関わる様子を、1つ選んでください。',1);if(!picked){ASSOCIATIONS.guideChoices.forEach((text,choiceIndex)=>button(text,()=>{sceneAPI.playAssociation(1,choiceIndex===0?'roll':'fit',true);playSound();setSession({associations:{...s.associations,guide:text}});card('頭の中なら、こんなことも。','案内板とりんごが動きでつながる。',text,1);primary('景色を覚えた →',()=>nextStage('associate',2));secondary('別の想像を選ぶ',()=>{setSession({associations:{...data.session.associations,guide:''}});render();});}));el.primary.hidden=true;}else primary('景色を覚えた →',()=>nextStage('associate',2));secondary('ひとつ前へ',()=>nextStage('associate',0));return;}
  card('自分で想像 · 3 / 3','鳥居と、かぎ。','柱とかぎがどう関わるか、頭の中で想像してください。短いメモは任意です。',2);const memo=field('任意のメモ',s.associations.torii||'');primary('この想像で結ぶ →',()=>{const token=renderToken,text=memo.value.trim().slice(0,120)||'自分で想像した';el.primary.disabled=true;sceneAPI.playAssociation(2,'sway',true);playSound();setSession({associations:{...s.associations,torii:text}});data.associations={...data.associations,...data.session.associations};save();setTimeout(()=>{if(token===renderToken&&data.session?.stage==='associate'&&data.session.index===2)nextStage('recall',0,{outcomes:[]});},prefs.reduced?50:800);});secondary('例を見る',()=>{memo.value=ASSOCIATIONS.toriiExample;el.feedback.textContent='この例を使っても、自分の想像へ書き換えてもかまいません。';});}

async function renderRecall(token){const s=data.session,{point,item}=currentPair(s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.mark(s.index,false);sceneAPI.setItem(s.index,false);card(`思い出す ${s.index+1} / 3`,`${point.label}に、何を置いた？`,'品物も名前も隠しています。頭の中で答えてから進みます。');if(s.choiceMode){renderChoiceHelp();return;}if(s.answerShown){showRecallAnswer();return;}primary('答えを見る',()=>{setSession({answerShown:true});showRecallAnswer();});secondary('選択肢で試す',()=>{setSession({choiceMode:true,assistedUsed:true});renderChoiceHelp();});}
function showRecallAnswer(){const s=data.session,token=renderToken,{point,item}=currentPair(s.index);sceneAPI.setItem(s.index,true,false);card(`答え · ${s.index+1} / 3`,`${point.label}は、${item.label}。`,'選択肢を使った場合は、自力想起としては数えません。',s.index);button('思い出せた',()=>finishRecall(s.assistedUsed?'choiceAssisted':'selfReported',s.index,token),{wide:true});button('もう一度',()=>finishRecall('forgotten',s.index,token),{wide:true});el.primary.hidden=true;}
function renderChoiceHelp(){const s=data.session,token=renderToken,{point}=currentPair(s.index);let resolved=false;card(`選択肢 · ${s.index+1} / 3`,`${point.label}に置いたものは？`,'ここで正解しても「選択肢の助けあり」として記録します。');const order=[2,0,1].map(value=>(value+s.index)%3);order.forEach(index=>{const choice=button(ITEMS[index].label,()=>{if(resolved)return;if(index!==s.index){choice.classList.add('wrong');choice.disabled=true;el.feedback.textContent='もう一度選べます。';return;}resolved=true;el.choices.querySelectorAll('button').forEach(value=>value.disabled=true);choice.classList.add('correct');sceneAPI.setItem(s.index,true,true);playSound('success');setTimeout(()=>finishRecall('choiceAssisted',s.index,token),prefs.reduced?60:450);},{art:index});});el.primary.hidden=true;}
function finishRecall(outcome,expectedIndex=data.session?.index,token=renderToken){if(token!==renderToken||data.session?.stage!=='recall'||data.session.index!==expectedIndex)return;const s=data.session,{point,item}=currentPair(s.index),outcomes=recordOutcome(s.outcomes,{placeId:point.id,itemId:item.id,outcome});renderToken++;playSound('success');if(s.index<2){data.session=stableSession({...s,index:s.index+1,outcomes,assistedUsed:false});saveSession();render();}else{const completedAt=new Date().toISOString();data.lastResult={outcomes,completedAt};if(s.reviewId){const review=data.reviews.find(row=>row.id===s.reviewId);if(review)data.reviews=upsertReview(data.reviews,rescheduleReview(review,outcomes));}data.session=stableSession({...s,stage:'result',index:2,outcomes,assistedUsed:false});save();render();}}
function renderResult(){sceneAPI.showOverview();const s=data.session,outcomes=s.outcomes.length?s.outcomes:data.lastResult?.outcomes||[],counts=outcomeCounts(outcomes),review=s.reviewId?data.reviews.find(row=>row.id===s.reviewId):null,reviewCopy=review?(lastSaveOK?` 次は ${review.dueDate} に表示します。`:' この画面では記録できましたが、閉じると次の予定は残りません。'):' 記録は混ぜずに残します。';card(s.reviewId?'今日の復習結果':'3地点の結果',`思い出せた ${counts.selfReported} / 3（自己申告）`,`選択肢の助けあり ${counts.choiceAssisted}つ／もう一度 ${counts.forgotten}つ。${reviewCopy}`);if(s.reviewId){primary('今日はここまで',()=>{data.session=null;save();renderLanding();});}else{primary('明日の復習を保存',()=>{const result=data.lastResult||{outcomes,completedAt:new Date().toISOString()},newReview=makeReview(result);data.reviews=upsertReview(data.reviews,newReview);const saved=save();el.feedback.textContent=saved?`${newReview.dueDate} に短い復習を表示します。`:'この画面では記録できましたが、閉じると復習予定は残りません。';el.primary.disabled=true;});secondary('自宅の3地点で試す',()=>nextStage('homeSetup',0));}button('同じ3地点を再挑戦',()=>{data.session=freshSession();saveSession();render();},{wide:true});if(!s.reviewId)button('今日はここまで',()=>{data.session=null;save();renderLanding();},{wide:true});}

function renderHomeSetup(){sceneAPI.showOverview();card('任意の応用練習','自宅の、よく知る3地点。','玄関、洗面台、机など。いつも通る順に3つ選びます。');const grid=document.createElement('div');grid.className='homeGrid';el.form.append(grid);const inputs=[0,1,2].map(index=>{const wrap=document.createElement('label');wrap.className='field';const span=document.createElement('span');span.textContent=`場所 ${index+1}`;const input=document.createElement('input');input.maxLength=24;input.value=data.homeNames[index]||'';wrap.append(span,input);grid.append(wrap);return input;});primary('この3地点で試す →',()=>{const result=validateHomeNames(inputs.map(input=>input.value));if(!result.ok){el.feedback.textContent=result.message;return;}data.homeNames=result.names;data.session=stableSession({...data.session,stage:'homeAssociate',index:0,homeOutcomes:[]});save();render();});secondary('結果へ戻る',()=>nextStage('result',2));}
function renderHomeAssociate(){sceneAPI.showOverview();const s=data.session,index=s.index;card(`頭の中で置く ${index+1} / 3`,`${data.homeNames[index]}に、${ITEMS[index].label}。`,'場所と品物が関わる様子を、自分で想像してください。',index);primary(index<2?'想像した →':'3地点を思い出す →',()=>index<2?nextStage('homeAssociate',index+1):nextStage('homeRecall',0,{homeOutcomes:[]}));if(index>0)secondary('ひとつ前へ',()=>nextStage('homeAssociate',index-1));}
function renderHomeRecall(){sceneAPI.showOverview();const s=data.session,index=s.index;if(s.answerShown){card(`答え ${index+1} / 3`,`${data.homeNames[index]}は、${ITEMS[index].label}。`,'頭の中の景色から出てきたかを、自分で記録します。',index);button('思い出せた',()=>finishHomeRecall('selfReported'),{wide:true});button('もう一度',()=>finishHomeRecall('forgotten'),{wide:true});el.primary.hidden=true;return;}card(`自宅で思い出す ${index+1} / 3`,`${data.homeNames[index]}に、何を置いた？`,'品物の名前は隠しています。頭の中で答えてください。');primary('答えを見る',()=>{setSession({answerShown:true});renderHomeRecall();});secondary('自宅の場所名を直す',()=>nextStage('homeSetup',0));}
function finishHomeRecall(outcome){const s=data.session,homeOutcomes=[...(s.homeOutcomes||[])];homeOutcomes[s.index]=outcome;if(s.index<2){data.session=stableSession({...s,index:s.index+1,homeOutcomes});saveSession();render();}else{data.lastHomeResult={outcomes:homeOutcomes,completedAt:new Date().toISOString()};data.session=stableSession({...s,stage:'homeResult',homeOutcomes});save();render();}}
function renderHomeResult(){sceneAPI.showOverview();const outcomes=data.session.homeOutcomes||[],self=outcomes.filter(value=>value==='selfReported').length;card('自宅での応用',`思い出せた ${self} / 3（自己申告）`,'同じ道順を、頭の中でもう一度たどってみましょう。');primary('入口へ戻る',()=>{data.session=null;save();renderLanding();});secondary('自宅でもう一度',()=>nextStage('homeAssociate',0,{homeOutcomes:[]}));}

$('#settingsButton').onclick=()=>el.settings.showModal();$('#closeSettings').onclick=()=>el.settings.close();
$('#soundSetting').checked=prefs.sound;$('#motionSetting').checked=prefs.reduced;
$('#soundSetting').onchange=event=>{prefs.sound=event.target.checked;save();if(prefs.sound)playSound();};
$('#motionSetting').onchange=event=>{prefs.reduced=event.target.checked;sceneAPI?.setReduced(prefs.reduced);save();};
$('#restart').onclick=()=>{el.settings.close();if(data.session){card('入口へ戻りますか？','途中の進みは保存されています。','「続きから」を選ぶと、同じ画面へ戻れます。');primary('入口へ戻る',showContinueLanding);secondary('練習を続ける',render);}};
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&el.settings.open)el.settings.close();});

async function boot(){try{sceneAPI=await createPalaceScene({container:el.world,reduced:prefs.reduced,onProgress:value=>$('#loadProgress').textContent=`木々と坂道 ${value}%`,onStats:value=>{if(inspect)$('#metrics').textContent=JSON.stringify({...value,stage:data.session?.stage||'landing',storageKey:STORAGE_KEY},null,2);},onError:()=>{}});el.loading.hidden=true;if(data.session)showContinueLanding();else renderLanding();}catch{el.loading.replaceChildren();const title=document.createElement('b');title.textContent='山の道を読み込めませんでした';const retry=document.createElement('button');retry.textContent='読み込み直す';retry.onclick=()=>location.reload();el.loading.append(title,retry);}}
boot();
