import {SET_FIRST,SET_TRAIL,COURSES,coursePoints,courseItems} from './route.js?v=trail6-20260925-final2';
import {createPalaceScene} from './scene.js?v=trail6-20260925-final2';
import {STORAGE_KEY,loadFrom,saveTo,makeReview,upsertReview,rescheduleReview,localDate} from './storage.js?v=trail6-20260925-final2';
import {ASSOCIATIONS,freshSession,stableSession,currentPair,outcomeCounts,recordOutcome,validateHomeNames,checkRoutePick} from './learning.js?v=trail6-20260925-final2';

const $=selector=>document.querySelector(selector);
const el={app:$('#app'),world:$('#world'),card:$('#actionCard'),title:$('#cardTitle'),text:$('#cardText'),eye:$('#eyebrow'),art:$('#itemArt'),form:$('#formArea'),choices:$('#choices'),feedback:$('#feedback'),primary:$('#primary'),secondary:$('#secondary'),travel:$('#travel'),loading:$('#loading'),progress:$('#progress'),progressLabel:$('#progressLabel'),saveWarning:$('#saveWarning'),settings:$('#settings')};
const loaded=loadFrom(localStorage);let data=loaded.data,sceneAPI,renderToken=0,audio,lastSaveOK=loaded.ok;
const osReduced=matchMedia('(prefers-reduced-motion: reduce)').matches,prefs={sound:data.prefs.sound===true,reduced:typeof data.prefs.reduced==='boolean'?data.prefs.reduced:osReduced};
const inspect=new URLSearchParams(location.search).has('inspect');$('#inspect').hidden=!inspect;if(!loaded.ok)showSaveWarning(loaded.warning);

function showSaveWarning(message){el.saveWarning.hidden=!message;el.saveWarning.textContent=message||'';}
function save(){data.prefs={...prefs};const result=saveTo(localStorage,data);lastSaveOK=result.ok;if(!result.ok)showSaveWarning(result.warning);return result.ok;}
function saveSession(){if(data.session)data.session.updatedAt=new Date().toISOString();save();}
function setSession(patch){data.session={...data.session,...patch,updatedAt:new Date().toISOString()};saveSession();}
function blank(){el.form.replaceChildren();el.choices.replaceChildren();el.feedback.textContent='';el.art.replaceChildren();el.card.classList.remove('landing');el.primary.hidden=false;el.secondary.hidden=true;}
function thumbIndex(setId,index){return setId===SET_TRAIL?index+3:index;}
function card(eye,title,text,art=-1,{landing=false}={}){blank();el.card.hidden=false;el.card.classList.toggle('landing',landing);el.eye.textContent=eye;el.title.textContent=title;el.text.textContent=text;if(art>=0&&sceneAPI?.thumbnails[art]){const image=new Image();image.src=sceneAPI.thumbnails[art];image.alt='';el.art.append(image);}}
function primary(label,handler){el.primary.textContent=label;el.primary.disabled=false;el.primary.onclick=()=>handler?.();}
function secondary(label,handler,css=''){el.secondary.hidden=!label;el.secondary.textContent=label;el.secondary.className=`textButton ${css}`.trim();el.secondary.onclick=()=>handler?.();}
function button(label,handler,{wide=false,art=-1}={}){const value=document.createElement('button');value.type='button';value.className=`choice${wide?' wide':''}`;if(art>=0&&sceneAPI.thumbnails[art]){const image=new Image();image.src=sceneAPI.thumbnails[art];image.alt='';value.append(image);}const span=document.createElement('span');span.textContent=label;value.append(span);value.onclick=handler;el.choices.append(value);return value;}
function field(label,value='',type='textarea'){const wrap=document.createElement('label'),caption=document.createElement('span'),input=document.createElement(type);wrap.className='field';caption.textContent=label;input.value=value;input.maxLength=type==='input'?24:120;wrap.append(caption,input);el.form.append(wrap);return input;}
function playSound(kind='step'){if(!prefs.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='success'?[523,659,784]:[440,554];notes.forEach((frequency,index)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),time=audio.currentTime+index*.1;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.001,time);gain.gain.linearRampToValueAtTime(.05,time+.02);gain.gain.exponentialRampToValueAtTime(.001,time+.48);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(time);oscillator.stop(time+.5);});}catch{/* optional */}}
function progress(stage){const step=stage==='preview'||stage==='routeCheck'?0:stage==='associate'?1:stage==='recall'||stage==='result'?2:-1,labels=stage.startsWith('home')?'自宅の3地点で応用':step===0?'場所を知る':step===1?'自分で結ぶ':step===2?'思い出す':'2つの道から選ぶ';el.progressLabel.textContent=labels;[...el.progress.querySelectorAll('li')].forEach((li,index)=>{li.classList.toggle('done',step>=0&&index<step);li.classList.toggle('current',index===step);});}
async function travel(point,label,token){el.card.hidden=true;el.travel.hidden=false;el.travel.textContent=label;sceneAPI.hideItems();sceneAPI.mark(point,true);await sceneAPI.moveTo(point);if(token!==renderToken)return false;el.travel.hidden=true;return true;}
function nextStage(stage,index=0,extra={}){data.session=stableSession({...data.session,stage,index,assistedUsed:false,...extra});saveSession();render();}
function startCourse(setId){data.session=freshSession(setId);saveSession();render();}

async function render(){const token=++renderToken,session=data.session;el.app.dataset.phase=session?.stage||'landing';progress(session?.stage||'landing');if(!session){renderLanding();return;}switch(session.stage){case'preview':await renderPreview(token);break;case'routeCheck':renderRouteCheck();break;case'associate':await renderAssociate(token);break;case'recall':await renderRecall(token);break;case'result':renderResult();break;case'homeSetup':renderHomeSetup();break;case'homeAssociate':renderHomeAssociate();break;case'homeRecall':renderHomeRecall();break;case'homeResult':renderHomeResult();break;default:data.session=null;save();renderLanding();}}
function renderLanding(){
  sceneAPI.showOverview();progress('landing');const today=localDate();card('体験版 · 6地点','どの道を歩きますか？','各コース3地点。景色を歩き、自分で結び、思い出します。',-1,{landing:true});el.primary.hidden=true;
  [SET_FIRST,SET_TRAIL].forEach(setId=>{const course=COURSES[setId],due=data.reviews.find(review=>review.setId===setId&&review.dueDate<=today);button(`${course.label}${due?' · 今日の復習':''}`,()=>{if(due){data.session={...freshSession(setId),stage:'recall',associations:{...data.associationsBySet[setId]},reviewId:due.id,reviewStep:due.step};saveSession();render();}else startCourse(setId);},{wide:true});});
  const previous=Object.values(data.lastResults).filter(result=>COURSES[result.setId]).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));if(previous.length)secondary('前回の結果を見る',()=>{const result=previous[0];data.session={...freshSession(result.setId),stage:'result',outcomes:result.outcomes};saveSession();render();});
}
function showContinueLanding(){renderToken++;sceneAPI.showOverview();const course=COURSES[data.session.setId];card('続きが保存されています',`${course.shortLabel}の途中から戻れます。`,'直前の安定した場面から再開します。',-1,{landing:true});primary('続きから →',render);secondary('途中を消してコース選択へ',()=>{card('途中の進みを消しますか？','このコースの途中経過を最初に戻します。','完了した結果と復習予定は残ります。');primary('途中を消す',()=>{data.session=null;save();renderLanding();});secondary('続きへ戻る',showContinueLanding);},'danger');}

async function renderPreview(token){const s=data.session,{point}=currentPair(s.setId,s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.hideItems();card(`下見 ${s.index+1} / 3`,point.label,point.cue);primary(s.index<2?'次の場所へ →':'順路を確かめる →',()=>s.index<2?nextStage('preview',s.index+1):nextStage('routeCheck',0,{routeOrder:[]}));if(s.index>0)secondary('ひとつ前へ',()=>nextStage('preview',s.index-1));}
function renderRouteCheck(){
  sceneAPI.showOverview();const s=data.session,points=coursePoints(s.setId),done=s.routeOrder.length;card('下見のあと',done===3?'順路がつながりました。':`${done+1}番目は、どこ？`,done===3?'坂道の3地点を順にたどります。':'見た順に選んでください。これは能力の評価ではありません。');
  if(done<3){[points[2],points[0],points[1]].forEach(point=>{const choice=button(point.label,()=>{const result=checkRoutePick(s.setId,s.routeOrder,point.id);if(!result.ok){choice.classList.add('wrong');el.feedback.textContent='もう一度、見た順を思い出します。';return;}setSession({routeOrder:result.order});playSound();renderRouteCheck();});if(s.routeOrder.includes(point.id))choice.disabled=true;});el.primary.hidden=true;secondary('下見に戻る',()=>nextStage('preview',0));}
  else{primary('品物と結ぶ →',()=>nextStage('associate',0));secondary('もう一度、下見する',()=>nextStage('preview',0));}
}

async function renderAssociate(token){
  const s=data.session,{point,item}=currentPair(s.setId,s.index),art=thumbIndex(s.setId,s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.mark(point,false);
  if(s.setId===SET_FIRST&&s.index===0){const watched=Boolean(s.associations.parking);if(watched)sceneAPI.playAssociation(s.setId,0,'swell',false);card('見本 · 1 / 3','車止めと、ぎゅうにゅう。',watched?ASSOCIATIONS.parking:'まず、場所と品物が作用する見本を見ます。',watched?art:-1);primary(watched?'景色を覚えた →':'見本を見る',()=>{if(watched){nextStage('associate',1);return;}el.primary.disabled=true;sceneAPI.playAssociation(s.setId,0,'swell',true);playSound();setSession({associations:{...s.associations,parking:ASSOCIATIONS.parking}});card('頭の中なら、こんなことも。','牛乳が大きくなって車止めへ。',ASSOCIATIONS.parking,art);primary('景色を覚えた →',()=>nextStage('associate',1));});return;}
  if(s.setId===SET_FIRST&&s.index===1){const picked=s.associations.guide;if(picked)sceneAPI.playAssociation(s.setId,1,picked===ASSOCIATIONS.guideChoices[0]?'roll':'fit',false);else sceneAPI.setItem(s.setId,1,true,false);card('選ぶ · 2 / 3','案内板と、りんご。',picked||'場所と品物が関わる様子を、1つ選んでください。',art);if(!picked){ASSOCIATIONS.guideChoices.forEach((text,index)=>button(text,()=>{el.choices.querySelectorAll('button').forEach(value=>value.disabled=true);sceneAPI.playAssociation(s.setId,1,index===0?'roll':'fit',true);playSound();setSession({associations:{...s.associations,guide:text}});card('頭の中なら、こんなことも。','案内板とりんごが動きでつながる。',text,art);primary('景色を覚えた →',()=>nextStage('associate',2));secondary('別の想像を選ぶ',()=>{setSession({associations:{...data.session.associations,guide:''}});render();});}));el.primary.hidden=true;}else primary('景色を覚えた →',()=>nextStage('associate',2));secondary('ひとつ前へ',()=>nextStage('associate',0));return;}
  sceneAPI.setItem(s.setId,s.index,true,false);const examples=s.setId===SET_FIRST?[null,null,ASSOCIATIONS.toriiExample]:[ASSOCIATIONS.trailheadExample,ASSOCIATIONS.logStepsExample,ASSOCIATIONS.streamBridgeExample],saved=s.associations[point.id]||'';
  card(`自分で想像 · ${s.index+1} / 3`,`${point.label}と、${item.label}。`,'場所と品物がどう関わるか想像します。短いメモは任意です。',art);const memo=field('任意のメモ',saved);
  primary(s.index<2?'この想像で次へ →':'この想像で結ぶ →',()=>{const expectedToken=renderToken,text=memo.value.trim().slice(0,120)||'自分で想像した';el.primary.disabled=true;sceneAPI.playAssociation(s.setId,s.index,'custom',true);playSound();setSession({associations:{...s.associations,[point.id]:text}});data.associationsBySet[s.setId]={...data.associationsBySet[s.setId],...data.session.associations};save();setTimeout(()=>{if(expectedToken!==renderToken||data.session?.stage!=='associate'||data.session.index!==s.index||data.session.setId!==s.setId)return;s.index<2?nextStage('associate',s.index+1):nextStage('recall',0,{outcomes:[]});},prefs.reduced?50:1350);});
  secondary('例を見る',()=>{memo.value=examples[s.index];el.feedback.textContent='この例を使っても、自分の想像へ書き換えてもかまいません。';});
}

async function renderRecall(token){const s=data.session,{point}=currentPair(s.setId,s.index);if(!await travel(point,`${point.label}へ向かっています`,token))return;sceneAPI.mark(point,false);sceneAPI.setItem(s.setId,s.index,false);card(`思い出す ${s.index+1} / 3`,`${point.label}に、何を置いた？`,'品物も名前も隠しています。頭の中で答えてから進みます。');if(s.choiceMode){renderChoiceHelp();return;}if(s.answerShown){showRecallAnswer();return;}primary('答えを見る',()=>{setSession({answerShown:true});showRecallAnswer();});secondary('選択肢で試す',()=>{setSession({choiceMode:true,assistedUsed:true});renderChoiceHelp();});}
function showRecallAnswer(){const s=data.session,token=renderToken,{point,item}=currentPair(s.setId,s.index);sceneAPI.setItem(s.setId,s.index,true,false);card(`答え · ${s.index+1} / 3`,`${point.label}は、${item.label}。`,'選択肢を使った場合は、自力想起としては数えません。',thumbIndex(s.setId,s.index));button('思い出せた',()=>finishRecall(s.assistedUsed?'choiceAssisted':'selfReported',s.index,token),{wide:true});button('もう一度',()=>finishRecall('forgotten',s.index,token),{wide:true});el.primary.hidden=true;}
function renderChoiceHelp(){
  const s=data.session,token=renderToken,{point}=currentPair(s.setId,s.index),items=courseItems(s.setId);let resolved=false;card(`選択肢 · ${s.index+1} / 3`,`${point.label}に置いたものは？`,'正解しても「選択肢の助けあり」として記録します。');
  [2,0,1].map(value=>(value+s.index)%3).forEach(index=>{const choice=button(items[index].label,()=>{if(resolved)return;if(index!==s.index){choice.classList.add('wrong');choice.disabled=true;el.feedback.textContent='もう一度選べます。';return;}resolved=true;el.choices.querySelectorAll('button').forEach(value=>value.disabled=true);choice.classList.add('correct');sceneAPI.setItem(s.setId,s.index,true,true);playSound('success');setTimeout(()=>finishRecall('choiceAssisted',s.index,token),prefs.reduced?60:450);},{art:thumbIndex(s.setId,index)});});el.primary.hidden=true;
}
function finishRecall(outcome,expectedIndex=data.session?.index,token=renderToken){
  if(token!==renderToken||data.session?.stage!=='recall'||data.session.index!==expectedIndex)return;const s=data.session,{point,item}=currentPair(s.setId,s.index),outcomes=recordOutcome(s.outcomes,{placeId:point.id,itemId:item.id,outcome});renderToken++;playSound('success');
  if(s.index<2){data.session=stableSession({...s,index:s.index+1,outcomes,assistedUsed:false});saveSession();render();return;}
  const completedAt=new Date().toISOString();data.lastResults[s.setId]={setId:s.setId,outcomes,completedAt};if(s.reviewId){const review=data.reviews.find(row=>row.id===s.reviewId);if(review)data.reviews=upsertReview(data.reviews,rescheduleReview(review,outcomes));}data.session=stableSession({...s,stage:'result',index:2,outcomes,assistedUsed:false});save();render();
}
function renderResult(){
  sceneAPI.showOverview();const s=data.session,result=data.lastResults[s.setId],outcomes=s.outcomes.length?s.outcomes:result?.outcomes||[],counts=outcomeCounts(outcomes),review=s.reviewId?data.reviews.find(row=>row.id===s.reviewId):null,reviewCopy=review?(lastSaveOK?` 次は ${review.dueDate} に表示します。`:' この画面では記録できましたが、閉じると次の予定は残りません。'):' 結果はコースごとに残します。';card(s.reviewId?`${COURSES[s.setId].shortLabel}の復習結果`:`${COURSES[s.setId].shortLabel}の結果`,`思い出せた ${counts.selfReported} / 3（自己申告）`,`選択肢の助けあり ${counts.choiceAssisted}つ／もう一度 ${counts.forgotten}つ。${reviewCopy}`);
  if(s.reviewId)primary('今日はここまで',()=>{data.session=null;save();renderLanding();});else{primary('明日の復習を保存',()=>{const current=result||{outcomes,completedAt:new Date().toISOString()},newReview=makeReview(current,s.setId);data.reviews=upsertReview(data.reviews,newReview);const saved=save();el.feedback.textContent=saved?`${newReview.dueDate} に短い復習を表示します。`:'この画面では記録できましたが、閉じると復習予定は残りません。';el.primary.disabled=true;});if(s.setId===SET_FIRST)secondary('自宅の3地点で試す',()=>nextStage('homeSetup',0));}
  if(s.setId===SET_FIRST)button('山道の3地点へ',()=>startCourse(SET_TRAIL),{wide:true});button('同じ3地点を再挑戦',()=>startCourse(s.setId),{wide:true});button('コース選択へ',()=>{data.session=null;save();renderLanding();},{wide:true});
}

function renderHomeSetup(){sceneAPI.showOverview();card('任意の応用練習','自宅の、よく知る3地点。','玄関、洗面台、机など。いつも通る順に3つ選びます。');const grid=document.createElement('div');grid.className='homeGrid';el.form.append(grid);const inputs=[0,1,2].map(index=>{const wrap=document.createElement('label'),span=document.createElement('span'),input=document.createElement('input');wrap.className='field';span.textContent=`場所 ${index+1}`;input.maxLength=24;input.value=data.homeNames[index]||'';wrap.append(span,input);grid.append(wrap);return input;});primary('この3地点で試す →',()=>{const result=validateHomeNames(inputs.map(input=>input.value));if(!result.ok){el.feedback.textContent=result.message;return;}data.homeNames=result.names;data.session=stableSession({...data.session,setId:SET_FIRST,stage:'homeAssociate',index:0,homeOutcomes:[]});save();render();});secondary('結果へ戻る',()=>nextStage('result',2));}
function renderHomeAssociate(){sceneAPI.showOverview();const index=data.session.index,item=courseItems(SET_FIRST)[index];card(`頭の中で置く ${index+1} / 3`,`${data.homeNames[index]}に、${item.label}。`,'場所と品物が関わる様子を、自分で想像してください。',index);primary(index<2?'想像した →':'3地点を思い出す →',()=>index<2?nextStage('homeAssociate',index+1):nextStage('homeRecall',0,{homeOutcomes:[]}));if(index>0)secondary('ひとつ前へ',()=>nextStage('homeAssociate',index-1));}
function renderHomeRecall(){sceneAPI.showOverview();const s=data.session,index=s.index,item=courseItems(SET_FIRST)[index];if(s.answerShown){card(`答え ${index+1} / 3`,`${data.homeNames[index]}は、${item.label}。`,'頭の中の景色から出てきたかを、自分で記録します。',index);button('思い出せた',()=>finishHomeRecall('selfReported'),{wide:true});button('もう一度',()=>finishHomeRecall('forgotten'),{wide:true});el.primary.hidden=true;return;}card(`自宅で思い出す ${index+1} / 3`,`${data.homeNames[index]}に、何を置いた？`,'品物の名前は隠しています。頭の中で答えてください。');primary('答えを見る',()=>{setSession({answerShown:true});renderHomeRecall();});secondary('自宅の場所名を直す',()=>nextStage('homeSetup',0));}
function finishHomeRecall(outcome){const s=data.session,homeOutcomes=[...(s.homeOutcomes||[])];homeOutcomes[s.index]=outcome;if(s.index<2){data.session=stableSession({...s,index:s.index+1,homeOutcomes});saveSession();render();}else{data.lastHomeResult={outcomes:homeOutcomes,completedAt:new Date().toISOString()};data.session=stableSession({...s,stage:'homeResult',homeOutcomes});save();render();}}
function renderHomeResult(){sceneAPI.showOverview();const outcomes=data.session.homeOutcomes||[],self=outcomes.filter(value=>value==='selfReported').length;card('自宅での応用',`思い出せた ${self} / 3（自己申告）`,'同じ道順を、頭の中でもう一度たどってみましょう。');primary('コース選択へ',()=>{data.session=null;save();renderLanding();});secondary('自宅でもう一度',()=>nextStage('homeAssociate',0,{homeOutcomes:[]}));}

$('#settingsButton').onclick=()=>el.settings.showModal();$('#closeSettings').onclick=()=>el.settings.close();$('#soundSetting').checked=prefs.sound;$('#motionSetting').checked=prefs.reduced;
$('#soundSetting').onchange=event=>{prefs.sound=event.target.checked;save();if(prefs.sound)playSound();};$('#motionSetting').onchange=event=>{prefs.reduced=event.target.checked;sceneAPI?.setReduced(prefs.reduced);save();};
$('#restart').onclick=()=>{el.settings.close();if(data.session){card('コース選択へ戻りますか？','途中の進みは保存されています。','「続きから」を選ぶと、同じ画面へ戻れます。');primary('選択画面を見る',showContinueLanding);secondary('練習を続ける',render);}};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&el.settings.open)el.settings.close();});
async function boot(){try{sceneAPI=await createPalaceScene({container:el.world,reduced:prefs.reduced,onProgress:value=>$('#loadProgress').textContent=`木々と坂道 ${value}%`,onStats:value=>{if(inspect)$('#metrics').textContent=JSON.stringify({...value,stage:data.session?.stage||'landing',setId:data.session?.setId||null,storageKey:STORAGE_KEY},null,2);},onError:()=>{}});el.loading.hidden=true;if(data.session)showContinueLanding();else renderLanding();}catch{el.loading.replaceChildren();const title=document.createElement('b'),retry=document.createElement('button');title.textContent='山の道を読み込めませんでした';retry.textContent='読み込み直す';retry.onclick=()=>location.reload();el.loading.append(title,retry);}}
boot();
