import {ROUTE,ITEMS,elevationAt} from './route.js?v=mountain15-20260926-assoc3';
import {createMountainScene} from './scene.js?v=mountain15-20260926-assoc3';
import {STORAGE_KEY,loadFrom,saveTo,freshSession,recordOutcome,makeReview,upsertReview,rescheduleReview,localDate} from './storage.js?v=mountain15-20260926-assoc3';
import {EXAMPLES,pair,counts,recallChoices} from './learning.js?v=mountain15-20260926-assoc3';
const $=s=>document.querySelector(s),el={card:$('#card'),kicker:$('#kicker'),title:$('#title'),copy:$('#copy'),body:$('#body'),actions:$('#actions'),walk:$('#walkControls'),destination:$('#destination'),counter:$('#counter'),warning:$('#warning'),loading:$('#loading')};
if(new URLSearchParams(location.search).has('inspect'))document.querySelector('#inspect').classList.add('visible');
const inspectMode=new URLSearchParams(location.search).has('inspect');
const loaded=loadFrom(localStorage);let data=loaded.data,scene,lastSave=loaded.ok,token=0,lastPositionSave=0,busy=false;const reduced=typeof data.prefs.reduced==='boolean'?data.prefs.reduced:matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){const r=saveTo(localStorage,data);lastSave=r.ok;if(!r.ok){el.warning.hidden=false;el.warning.textContent=r.warning;}return r.ok;}
function session(patch){data.session={...data.session,...patch,updatedAt:new Date().toISOString()};save();}
function clear(){el.body.replaceChildren();el.actions.replaceChildren();el.walk.hidden=true;el.card.classList.remove('compact','learning');}
function view(kicker,title,copy){clear();el.card.hidden=false;el.kicker.textContent=kicker;el.title.textContent=title;el.copy.textContent=copy;}
function btn(label,fn,cls='primary'){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=e=>{if(busy)return;fn?.(e,b)};el.actions.append(b);return b;}
function relationText(s,point){return s.associations?.[point.id]||data.associations?.[point.id]||EXAMPLES[point.id];}
function relationNote(s,point){const p=document.createElement('p');p.className='example';p.textContent=`連想：${relationText(s,point)}`;el.body.append(p);}
function associationDemo(index,parent){const button=document.createElement('button');button.type='button';button.className='associationDemo';button.textContent='連想例を動かす';let running=false,runId=0;button.onclick=()=>{if(running||data.session?.phase!=='arrived-learn'||data.session.index!==index)return;running=true;button.disabled=true;const expectedToken=token,currentRun=++runId,point=ROUTE[index],variant=point.id==='guide'&&relationText(data.session,point).includes('はまる')?'fit':'default',duration=scene.playAssociation(index,true,variant);button.textContent=duration?'動きを再生中':'軽減設定：完成位置を表示';setTimeout(()=>{if(currentRun!==runId||expectedToken!==token||!button.isConnected)return;running=false;button.disabled=false;button.textContent='もう一度見る';},Math.max(200,duration+120));};button.resetDemo=()=>{runId++;running=false;button.disabled=false;button.textContent='連想例を動かす';};parent.append(button);return button;}
function start(mode='learn',review=null){data.session=freshSession(mode);if(review){data.session.reviewId=review.id;data.session.associations={...data.associations};}save();scene.setPosition(data.session.position);render();}
function stopZ(index){return Math.min(5,ROUTE[index].scene.position[2]+ROUTE[index].scene.stopOffset);}
function travel(){const s=data.session,p=ROUTE[s.index],recall=s.mode==='review'||s.phase.includes('recall');scene.hideItems();el.card.classList.remove('learning');el.card.classList.add('compact');el.card.hidden=false;el.kicker.textContent=recall?'同じ道で思い出す':'山頂へ歩く';el.title.textContent=`次は ${p.label}`;el.copy.textContent=p.cue;el.body.replaceChildren();el.actions.replaceChildren();el.walk.hidden=false;el.destination.textContent=`${s.index+1} / 15　${p.label}`;el.counter.textContent=`標高 ${p.elevation.toFixed(1)}m`;
 el.counter.textContent=`標高 ${elevationAt(scene.getPosition().z).toFixed(1)}m`;
 const go=$('#go'),back=$('#back'),stop=$('#stop');go.onclick=()=>scene.walk(-1,stopZ(s.index));back.onpointerdown=e=>{back.setPointerCapture(e.pointerId);scene.walk(1)};for(const type of ['pointerup','pointercancel','pointerleave'])back[`on${type}`]=()=>scene.stop();stop.onclick=()=>scene.stop();}
function arriveLearn(){const s=data.session,{point,item}=pair(s.index);scene.showItem(s.index,true);view(`場所 ${s.index+1} / 15`,`${point.label} × ${item.label}`,point.cue);el.card.classList.add('learning');const example=document.createElement('p');example.className='example';example.textContent=relationText(s,point);if(s.index<2){el.body.append(example);associationDemo(s.index,el.body);}else{const hint=document.createElement('details'),sum=document.createElement('summary');sum.textContent='連想の例を見る';hint.append(sum,example);const demo=associationDemo(s.index,hint);hint.ontoggle=()=>{if(hint.open)demo.click();else{demo.resetDemo();scene.showItem(s.index,true);}};el.body.append(hint);}
 if(s.index===1){const group=document.createElement('div');group.className='miniChoices';['りんごが枠を転がる','大きなりんごが枠にはまる'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{if(group.dataset.chosen)return;group.dataset.chosen='1';session({associations:{...s.associations,[point.id]:t}});example.textContent=t;group.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('selected');scene.playAssociation(s.index,true,t.includes('はまる')?'fit':'default')};group.append(b)});el.body.append(group);}
 const details=document.createElement('details'),summary=document.createElement('summary'),memo=document.createElement('textarea');summary.textContent='自分の連想をメモ（任意）';memo.maxLength=140;memo.value=s.associations[point.id]||'';memo.placeholder='場所と品物が関わる様子';memo.oninput=()=>{if(data.session?.phase!=='arrived-learn'||data.session.index!==s.index)return;data.session.associations={...data.session.associations,[point.id]:memo.value};data.associations={...data.associations,[point.id]:memo.value};save();};details.append(summary,memo);el.body.append(details);
 btn(s.index===14?'15個を結んだ →':'次の場所へ →',()=>{if(data.session?.phase!=='arrived-learn'||data.session.index!==s.index)return;scene.hideItems();if(s.index===14){data.associations={...data.associations,...data.session.associations};session({phase:'summit'});render();}else{const pos=scene.getPosition();scene.setPosition({...pos,yaw:0,pitch:0});session({phase:'travel-learn',index:s.index+1,position:scene.getPosition()});render();}});if(s.index===8)btn('景色を見る',()=>{if(document.querySelector('#returnView'))return;scene.hideItems();el.card.hidden=true;scene.face([10,8,12]);const b=document.createElement('button');b.id='returnView';b.textContent='学習へ戻る';b.onclick=()=>{b.remove();scene.face(point.scene.itemPosition);render()};document.body.append(b);},'secondary');}
function summit(){scene.hideItems();view('山頂に到着', '15個を結びました。','今度は品物を隠し、同じ道をふもとからもう一度登ります。');btn('ふもとへ戻って思い出す →',()=>{const s=data.session;data.session={...freshSession('review'),phase:'travel-recall',associations:{...s.associations},position:{x:0,z:5,yaw:0,pitch:0}};save();scene.setPosition(data.session.position);render();});}
function arriveRecall(){const s=data.session,{point}=pair(s.index);scene.hideItems();view(`思い出す ${s.index+1} / 15`,`${point.label}に置いたものは？`,'品物と名前は隠しています。頭の中で答えてください。');el.card.classList.add('learning');if(s.answerShown){answer();return;}btn('答えを見る',()=>{if(data.session?.phase!=='arrived-recall'||data.session.index!==s.index)return;session({answerShown:true});render();});btn('選択肢で試す',()=>{if(data.session?.phase!=='arrived-recall'||data.session.index!==s.index)return;session({choiceUsed:true});choices();},'secondary');}
function choices(){const s=data.session,{point}=pair(s.index);view(`選択肢 ${s.index+1} / 15`,`${point.label}に置いたものは？`,'正解しても「助けあり」として記録します。');let done=false;recallChoices(s.index).forEach(item=>btn(item.label,(event,button)=>{if(done||data.session?.phase!=='arrived-recall'||data.session.index!==s.index)return;if(item.id!==ROUTE[s.index].item.id){button.disabled=true;return;}done=true;el.actions.querySelectorAll('button').forEach(b=>b.disabled=true);session({choiceUsed:true,answerShown:true,pendingOutcome:'choiceAssisted'});render();},'choice'));}
function answer(){const s=data.session,{point,item}=pair(s.index);scene.showItem(s.index,true);view(`答え ${s.index+1} / 15`,`${point.label}は ${item.label}`,'品物と連想を見てから、記録して次へ進みます。');el.card.classList.add('learning');relationNote(s,point);if(s.pendingOutcome){const label=s.pendingOutcome==='selfReported'?'「思い出せた」':s.pendingOutcome==='choiceAssisted'?'「助けあり」':'「もう一度」';const note=document.createElement('p');note.className='outcomeNote';note.textContent=`${label}として記録します。`;el.body.append(note);const expectedToken=token,next=btn(s.index<14?'次の場所へ →':'結果を見る →',()=>advanceOutcome(s.index));next.disabled=true;setTimeout(()=>{if(expectedToken===token&&next.isConnected)next.disabled=false;},500);return;}btn('思い出せた',()=>stageOutcome(s.choiceUsed?'choiceAssisted':'selfReported',s.index));btn('もう一度',()=>stageOutcome('forgotten',s.index),'secondary');}
function stageOutcome(outcome,expectedIndex){if(busy||data.session?.phase!=='arrived-recall'||data.session.index!==expectedIndex||data.session.pendingOutcome)return;busy=true;session({pendingOutcome:outcome,answerShown:true,choiceUsed:data.session.choiceUsed||outcome==='choiceAssisted'});render();busy=false;}
function advanceOutcome(expectedIndex){const s=data.session;if(busy||s?.phase!=='arrived-recall'||s.index!==expectedIndex||!s.pendingOutcome)return;busy=true;const p=ROUTE[s.index],outcomes=recordOutcome(s.outcomes,{placeId:p.id,itemId:p.item.id,outcome:s.pendingOutcome});scene.hideItems();if(s.index<14){const pos=scene.getPosition();scene.setPosition({...pos,yaw:0,pitch:0});data.session={...s,index:s.index+1,phase:'travel-recall',outcomes,choiceUsed:false,answerShown:false,pendingOutcome:null,position:scene.getPosition()};save();busy=false;render();return;}const result={outcomes,completedAt:new Date().toISOString()};data.lastResult=result;if(s.reviewId){const review=data.reviews.find(r=>r.id===s.reviewId);if(review)data.reviews=upsertReview(data.reviews,rescheduleReview(review,outcomes));}else data.reviews=upsertReview(data.reviews,makeReview(result));data.session={...s,phase:'result',outcomes,pendingOutcome:null};save();busy=false;render();}
function result(){scene.hideItems();const c=counts(data.session.outcomes),review=data.reviews.find(r=>r.id===(data.session.reviewId||data.reviews.at(-1)?.id));view('登山の結果',`自力で思い出せた ${c.selfReported} / 15`,`助けあり ${c.choiceAssisted}／もう一度 ${c.forgotten}。${lastSave&&review?`次は ${review.dueDate} に歩きます。`:'保存できない場合はこの画面を閉じると予定が残りません。'}`);btn('入口へ',()=>{data.session=null;save();landing();});}
function landing(){scene.hideItems();const due=data.reviews.find(r=>r.dueDate<=localDate());view('15地点・約10〜15分','山頂まで歩く','坂道を登り、15の景色と品物を結びます。途中で止まり、周りを見渡せます。');if(loaded.hasLegacy){const p=document.createElement('p');p.className='legacy';p.textContent='以前の練習記録はそのまま残ります。';el.body.append(p);}if(due)btn('今日の復習を歩く →',()=>start('review',due));else btn('登山を始める →',()=>start('learn'));if(data.lastResult)btn('前回の結果を見る',()=>{data.session={...freshSession(),phase:'result',outcomes:data.lastResult.outcomes};render();},'secondary');}
function render(){token++;const s=data.session;if(!s){landing();return;}if(s.phase.startsWith('travel'))travel();else if(s.phase==='arrived-learn')arriveLearn();else if(s.phase==='summit')summit();else if(s.phase==='arrived-recall')arriveRecall();else if(s.phase==='result')result();}
function reached(){const s=data.session;if(!s||!s.phase.startsWith('travel'))return;scene.face(ROUTE[s.index].scene.itemPosition);session({phase:s.phase==='travel-learn'?'arrived-learn':'arrived-recall',position:scene.getPosition()});render();}
document.addEventListener('keydown',e=>{if(!data.session?.phase.startsWith('travel')||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)||$('#settingsDialog').open)return;if(['w','W','ArrowUp'].includes(e.key)){e.preventDefault();scene.walk(-1,stopZ(data.session.index));}if(['s','S','ArrowDown'].includes(e.key)){e.preventDefault();scene.walk(1);}});document.addEventListener('keyup',e=>{if(['w','W','s','S','ArrowUp','ArrowDown'].includes(e.key))scene.stop();});
$('#settings').onclick=()=>{scene.stop();$('#settingsDialog').showModal()};$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#restart').onclick=()=>{if(confirm('現在の登山を最初に戻しますか？')){data.session=freshSession();save();scene.setPosition(data.session.position);$('#settingsDialog').close();render();}};$('#reduced').checked=reduced;$('#reduced').onchange=e=>{data.prefs.reduced=e.target.checked;scene.setReduced(e.target.checked);save();};addEventListener('blur',()=>scene?.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden){scene?.stop();save();}});addEventListener('pagehide',save);
async function boot(){try{scene=await createMountainScene({container:$('#world'),reduced,position:data.session?.position||{z:5},onProgress:n=>$('#loadProgress').textContent=`${n}%`,onArrive:reached,onPosition:p=>{if(!data.session)return;data.session.position=p;el.counter.textContent=`標高 ${elevationAt(p.z).toFixed(1)}m`;const now=Date.now();if(now-lastPositionSave>1000){lastPositionSave=now;save();}},onStats:s=>{if(inspectMode)$('#metrics').textContent=JSON.stringify({...s,storageKey:STORAGE_KEY},null,2)}});el.loading.hidden=true;if(!loaded.ok){el.warning.hidden=false;el.warning.textContent=loaded.warning;}render();}catch(e){el.loading.innerHTML='<b>山道を読み込めませんでした</b><button onclick="location.reload()">読み込み直す</button>';console.error(e);}}
boot();
