import * as THREE from 'three';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {DRACOLoader} from './vendor/loaders/DRACOLoader.js';
import {ROUTE,ITEMS,elevationAt} from './route.js?v=mountain15-20260926-b5';
const v=a=>new THREE.Vector3(...a);
export async function createMountainScene({container,reduced=false,position,onProgress=()=>{},onPosition=()=>{},onArrive=()=>{},onStats=()=>{}}){
 let renderer,scene,camera,sun,model,last=0,walking=0,targetZ=null,drag=null,yaw=position?.yaw||0,pitch=position?.pitch||0,currentReduced=reduced;
 const state={x:position?.x||0,z:position?.z??5,items:[],thumbs:[],stats:{assetBytes:0,drawCalls:0,triangles:0}};
 renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;container.append(renderer.domElement);
 scene=new THREE.Scene();scene.fog=new THREE.Fog('#cad7c3',30,175);camera=new THREE.PerspectiveCamera(innerWidth<640?62:55,innerWidth/innerHeight,.1,600);scene.add(new THREE.HemisphereLight(0xfff4dd,0x60775a,1.8));sun=new THREE.DirectionalLight(0xffe1b2,2.45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:22,bottom:-18,near:1,far:70});scene.add(sun,sun.target);makeSky(scene);
 const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath('./vendor/draco/');loader.setDRACOLoader(draco);const gltf=await loader.loadAsync('./assets/mountain15.glb?v=mountain15-20260926-b5',p=>{if(p.total){state.stats.assetBytes=p.total;onProgress(Math.round(p.loaded/p.total*100));}});draco.dispose();model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.receiveShadow=true;o.castShadow=!o.name.includes('Distant')&&!o.name.includes('Water');}});
 ITEMS.forEach((item,index)=>{const source=model.getObjectByName(item.model);if(!source)throw new Error(`Missing ${item.model}`);source.visible=false;const copy=source.clone(true),point=ROUTE[index];copy.visible=false;copy.position.copy(v(point.scene.itemPosition));copy.scale.setScalar(item.baseScale);copy.userData.base=copy.position.y;scene.add(copy);state.items.push(copy);});
 bind();animate(performance.now());
 function animate(now){requestAnimationFrame(animate);const dt=Math.min(last?(now-last)/1000:0,.05);last=now;if(document.hidden){walking=0;return;}if(walking){const speed=currentReduced?2.0:3.5,next=THREE.MathUtils.clamp(state.z+walking*speed*dt,-110,5);state.z=targetZ===null?next:(walking<0?Math.max(targetZ,next):Math.min(targetZ,next));if(targetZ!==null&&Math.abs(state.z-targetZ)<.01){state.z=targetZ;walking=0;const done=targetZ;targetZ=null;onArrive(done);}onPosition({x:state.x,z:state.z,yaw,pitch});}
   const eye=elevationAt(state.z)+1.60;camera.position.set(state.x,eye,state.z);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;sun.target.position.set(state.x,eye-1,state.z-4);sun.position.set(state.x-10,eye+17,state.z+9);sun.target.updateMatrixWorld();renderer.render(scene,camera);state.stats.drawCalls=renderer.info.render.calls;state.stats.triangles=renderer.info.render.triangles;onStats(state.stats);
 }
 function bind(){container.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];container.setPointerCapture(e.pointerId);});container.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-drag[1])*.003,-.65,.65);drag=[e.clientX,e.clientY];onPosition({x:state.x,z:state.z,yaw,pitch});});for(const type of ['pointerup','pointercancel'])container.addEventListener(type,()=>drag=null);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<640?62:55;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});}
 function walk(direction,toZ=null){walking=direction;targetZ=toZ;}
 function stop(){walking=0;targetZ=null;onPosition({x:state.x,z:state.z,yaw,pitch});}
 function setPosition(pos){state.x=pos.x??0;state.z=pos.z??5;yaw=pos.yaw??yaw;pitch=pos.pitch??pitch;onPosition({x:state.x,z:state.z,yaw,pitch});}
 function face(target){const dx=target[0]-state.x,dz=target[2]-state.z,flat=Math.hypot(dx,dz),eye=elevationAt(state.z)+1.60;yaw=Math.atan2(-dx,-dz);pitch=THREE.MathUtils.clamp(Math.atan2(target[1]-eye,Math.max(.01,flat))-.08,-.46,.22);onPosition({x:state.x,z:state.z,yaw,pitch});}
 function showItem(index,show=true,pop=false){state.items.forEach((o,i)=>o.visible=show&&i===index);if(show&&pop&&!currentReduced){const o=state.items[index],base=o.scale.x;o.scale.setScalar(base*.15);let t=0;const tick=()=>{t+=.08;o.scale.setScalar(base*Math.min(1,.15+t));if(t<.85)requestAnimationFrame(tick)};tick();}}
 function hideItems(){state.items.forEach(o=>o.visible=false);}
 return {walk,stop,setPosition,face,showItem,hideItems,setReduced:v=>currentReduced=v===true,getPosition:()=>({x:state.x,z:state.z,yaw,pitch}),thumbnails:state.thumbs,stats:state.stats};
}
function makeSky(scene){const g=new THREE.SphereGeometry(220,24,12),m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#8fc0d0')},bottom:{value:new THREE.Color('#ede7ce')}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(p).y*1.5,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'});scene.add(new THREE.Mesh(g,m));}
