import * as THREE from 'three';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {DRACOLoader} from './vendor/loaders/DRACOLoader.js';
import {ROUTE,ITEMS,elevationAt} from './route.js?v=mountain15-20260926-assoc3';
import {ASSOCIATION_MOTIONS} from './learning.js?v=mountain15-20260926-assoc3';
const v=a=>new THREE.Vector3(...a);
export async function createMountainScene({container,reduced=false,position,onProgress=()=>{},onPosition=()=>{},onArrive=()=>{},onStats=()=>{}}){
 let renderer,scene,camera,sun,model,last=0,walking=0,targetZ=null,drag=null,yaw=position?.yaw||0,pitch=position?.pitch||0,currentReduced=reduced;
 const state={x:position?.x||0,z:position?.z??5,items:[],thumbs:[],stats:{assetBytes:0,drawCalls:0,triangles:0}};
 renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;container.append(renderer.domElement);
 scene=new THREE.Scene();scene.fog=new THREE.Fog('#cad7c3',30,175);camera=new THREE.PerspectiveCamera(innerWidth<640?62:55,innerWidth/innerHeight,.1,600);scene.add(new THREE.HemisphereLight(0xfff4dd,0x60775a,1.8));sun=new THREE.DirectionalLight(0xffe1b2,2.45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:22,bottom:-18,near:1,far:70});scene.add(sun,sun.target);makeSky(scene);
 const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath('./vendor/draco/');loader.setDRACOLoader(draco);const gltf=await loader.loadAsync('./assets/mountain15.glb?v=mountain15-20260926-assoc3',p=>{if(p.total){state.stats.assetBytes=p.total;onProgress(Math.min(100,Math.max(0,Math.round(p.loaded/p.total*100))));}});draco.dispose();model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.receiveShadow=true;o.castShadow=!o.name.includes('Distant')&&!o.name.includes('Water');}});
 ITEMS.forEach((item,index)=>{const source=model.getObjectByName(item.model);if(!source)throw new Error(`Missing ${item.model}`);source.visible=false;const copy=source.clone(true),point=ROUTE[index];copy.visible=false;copy.position.copy(v(point.scene.itemPosition));copy.scale.setScalar(item.baseScale);copy.userData.home=copy.position.clone();copy.userData.baseScale=item.baseScale;copy.userData.association=null;scene.add(copy);state.items.push(copy);});
 bind();animate(performance.now());
 function animate(now){requestAnimationFrame(animate);const dt=Math.min(last?(now-last)/1000:0,.05);last=now;if(document.hidden){walking=0;return;}if(walking){const speed=currentReduced?2.0:3.5,next=THREE.MathUtils.clamp(state.z+walking*speed*dt,-110,5);state.z=targetZ===null?next:(walking<0?Math.max(targetZ,next):Math.min(targetZ,next));if(targetZ!==null&&Math.abs(state.z-targetZ)<.01){state.z=targetZ;walking=0;const done=targetZ;targetZ=null;onArrive(done);}onPosition({x:state.x,z:state.z,yaw,pitch});}
   updateAssociations(dt);const eye=elevationAt(state.z)+1.60;camera.position.set(state.x,eye,state.z);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;sun.target.position.set(state.x,eye-1,state.z-4);sun.position.set(state.x-10,eye+17,state.z+9);sun.target.updateMatrixWorld();renderer.render(scene,camera);state.stats.drawCalls=renderer.info.render.calls;state.stats.triangles=renderer.info.render.triangles;onStats(state.stats);
 }
 function bind(){container.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];container.setPointerCapture(e.pointerId);});container.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-drag[1])*.003,-.65,.65);drag=[e.clientX,e.clientY];onPosition({x:state.x,z:state.z,yaw,pitch});});for(const type of ['pointerup','pointercancel'])container.addEventListener(type,()=>drag=null);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<640?62:55;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});}
 function walk(direction,toZ=null){walking=direction;targetZ=toZ;}
 function stop(){walking=0;targetZ=null;onPosition({x:state.x,z:state.z,yaw,pitch});}
 function setPosition(pos){state.x=pos.x??0;state.z=pos.z??5;yaw=pos.yaw??yaw;pitch=pos.pitch??pitch;onPosition({x:state.x,z:state.z,yaw,pitch});}
 function face(target){const dx=target[0]-state.x,dz=target[2]-state.z,flat=Math.hypot(dx,dz),eye=elevationAt(state.z)+1.60;yaw=Math.atan2(-dx,-dz);pitch=THREE.MathUtils.clamp(Math.atan2(target[1]-eye,Math.max(.01,flat))-.08,-.46,.22);onPosition({x:state.x,z:state.z,yaw,pitch});}
 function resetItem(o,visible=o.visible){o.userData.association=null;o.position.copy(o.userData.home);o.scale.setScalar(o.userData.baseScale);o.rotation.set(0,0,0);o.visible=visible;}
 function showItem(index,show=true){state.items.forEach((o,i)=>resetItem(o,show&&i===index));}
 function hideItems(){state.items.forEach(o=>resetItem(o,false));}
 function playAssociation(index,animate=true,variant='default'){showItem(index,true);const o=state.items[index],point=ROUTE[index],baseSpec=ASSOCIATION_MOTIONS[point.id];if(!o||!baseSpec)return 0;const spec=point.id==='guide'&&variant==='fit'?{...baseSpec,mode:'frameFit',from:[0,-.20,.62],to:[.28,.08,0],scaleFrom:1.42,scaleTo:.92}:baseSpec,home=o.userData.home,base=o.userData.baseScale,from=home.clone().add(v(spec.from)),to=home.clone().add(v(spec.to)),fromScale=new THREE.Vector3(base*spec.scaleFrom,base*spec.scaleFrom,base*spec.scaleFrom),toScale=new THREE.Vector3(base*spec.scaleTo,base*spec.scaleTo,base*spec.scaleTo);if(!animate||currentReduced){o.position.copy(to);o.scale.copy(toScale);applyFinalRotation(o,spec.mode);return 0;}o.position.copy(from);o.scale.copy(fromScale);o.userData.association={mode:spec.mode,from,to,fromScale,toScale,time:0,duration:spec.duration};return Math.round(spec.duration*1000);}
 function applyFinalRotation(o,mode){o.rotation.set(0,0,0);if(mode==='umbrellaHook')o.rotation.z=-.18;else if(mode==='keySwing')o.rotation.z=.10;else if(mode==='ribbonWrap')o.rotation.y=.35;else if(mode==='letterBurst')o.rotation.x=-.08;}
 function updateAssociations(dt){for(const o of state.items){const a=o.userData.association;if(!a||!o.visible)continue;a.time=Math.min(a.duration,a.time+dt);const p=a.duration?a.time/a.duration:1,e=p*p*(3-2*p);o.position.lerpVectors(a.from,a.to,e);o.scale.lerpVectors(a.fromScale,a.toScale,e);o.rotation.set(0,0,0);switch(a.mode){case'swellRide':o.position.y+=Math.sin(p*Math.PI)*.20;break;case'frameRoll':o.rotation.z=-p*Math.PI*4;break;case'frameFit':o.position.y+=Math.sin(p*Math.PI)*.22;o.rotation.z=(1-p)*-.18;break;case'keySwing':o.rotation.z=Math.sin(p*Math.PI*5)*(1-p)*.62;break;case'umbrellaHook':o.position.y+=Math.sin(p*Math.PI)*.35;o.rotation.z=-.65*(1-p)-.18*p;break;case'bootSteps':o.position.y+=Math.abs(Math.sin(p*Math.PI*5))*(1-p)*.55;break;case'bridgeRing':o.rotation.z=Math.sin(p*Math.PI*7)*(1-p)*.48;break;case'breadRise':o.position.y+=Math.sin(p*Math.PI)*.18;o.rotation.y=Math.sin(p*Math.PI)*.18;break;case'watchFit':o.rotation.y=p*Math.PI*2;o.scale.multiplyScalar(1+Math.sin(p*Math.PI)*.18);break;case'binocularExtend':o.scale.z*=.72+.28*e;o.position.z-=Math.sin(p*Math.PI)*.18;break;case'ballBounce':o.position.y+=Math.abs(Math.sin(p*Math.PI*6))*(1-p)*.72;o.rotation.x=p*Math.PI*5;break;case'brushScrub':o.position.x+=Math.sin(p*Math.PI*8)*(1-p)*.10;break;case'hatDrop':o.rotation.z=(1-p)*-.45;o.position.y+=Math.sin(p*Math.PI)*.12;break;case'ribbonWrap':o.position.x+=Math.sin(p*Math.PI*2)*(1-p)*.48;o.position.z+=Math.cos(p*Math.PI*2)*(1-p)*.30;o.rotation.y=p*Math.PI*2;break;case'letterBurst':o.position.y+=Math.sin(p*Math.PI)*.38;o.rotation.x=(1-p)*-.55;break;case'starGlow':o.position.x+=Math.sin(p*Math.PI*2)*(1-p)*.22;o.position.y+=Math.sin(p*Math.PI)*.28;o.rotation.z=p*Math.PI*2;o.scale.multiplyScalar(1+Math.sin(p*Math.PI*2)*.20*(1-p));break;}if(p>=1){o.userData.association=null;o.position.copy(a.to);o.scale.copy(a.toScale);applyFinalRotation(o,a.mode);}}
 }
 function setReduced(value){currentReduced=value===true;state.items.forEach(o=>{if(o.visible)resetItem(o,true);});}
 return {walk,stop,setPosition,face,showItem,playAssociation,hideItems,setReduced,getPosition:()=>({x:state.x,z:state.z,yaw,pitch}),thumbnails:state.thumbs,stats:state.stats};
}
function makeSky(scene){const g=new THREE.SphereGeometry(220,24,12),m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#8fc0d0')},bottom:{value:new THREE.Color('#ede7ce')}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(p).y*1.5,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'});scene.add(new THREE.Mesh(g,m));}
